language: ruby
cache: bundler
bundler_args: --without documentation production
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - rbx
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
script:
  - bundle exec rspec
before_install: gem update bundler
